spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/finance_db
    username: postgres
    password: Killerhack12345
    driver-class-name: org.postgresql.Driver

  jdbc:
    initialization-mode: always
  data:
    jdbc:
      repositories:
        enabled: true
server:
  port: 8080