spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/finance_db
    username: postgres
    password: Killerhack12345
    driver-class-name: org.postgresql.Driver

  jdbc:
    initialization-mode: always
  data:
    jdbc:
      repositories:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework: DEBUG

server:
  port: 8080
  error:
      include-message: always
      include-stacktrace: always
